name: gaze_prf
channels:
  - conda-forge
dependencies:
  - python=3.9  # specify your Python version
  - tensorflow
  - tensorflow-probability
  - pandas
  - seaborn
  - tqdm
  - pip  # ensure pip is installed in the environment
  - ipykernel
  - nilearn
  - pip:
      - git+https://github.com/Gilles86/braincoder
      - git+https://github.com/mszinte/gaze_prf